# Generated by Django 5.2.13 on 2026-04-12 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI - Contrat à Durée Indéterminée'), ('CDD', 'CDD - Contrat à Durée Déterminée'), ('INTERIM', 'Intérim'), ('STAGE', 'Stage'), ('APPRENTISSAGE', 'Apprentissage'), ('FREELANCE', 'Freelance')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_currency', models.CharField(default='EUR', max_length=3)),
                ('working_hours', models.DecimalField(decimal_places=2, default=35.0, max_digits=5)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('job_description', models.TextField(blank=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
